title: An치lisis de Temperaturas - Jenn Mual
description: Visualizaci칩n de datos clim치ticos semanales de Cali
baseurl: "" 
url: "https://jennmual.github.io"
github_username: jennmual

# Configuraci칩n de tema (si usas Jekyll)
theme: minima
plugins:
  - jekyll-feed